import { SiteNav } from "../_components/SiteNav";
import { SiteFooter } from "../_components/SiteFooter";
import { PRO_PRICE_USD, PRO_SCANS_PER_MONTH } from "../_lib/pricing";

export const metadata = {
  title: "Terms & Conditions",
  description: "Read Thynkk's terms of service — what you can do with your account, how subscriptions work, and our fair use policy.",
  alternates: { canonical: "https://thynkk.co/terms" },
  robots: { index: false },
};

export default function TermsPage() {
  return (
    <div className="min-h-dvh bg-[#020617] text-[#F8FAFC]">
      <SiteNav />

      <main className="max-w-3xl mx-auto px-6 pt-36 pb-24">
        <p className="text-xs font-mono text-[#6366F1] uppercase tracking-widest mb-3">Legal</p>
        <h1 className="font-mono text-4xl font-bold mb-2">Terms &amp; Conditions</h1>
        <p className="text-sm text-[#475569] mb-12">Last updated: June 2026</p>

        <div className="prose prose-invert max-w-none space-y-10 text-[#CBD5E1] text-sm leading-relaxed">

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Thynkk (&ldquo;the Service&rdquo;), you agree to be bound by these Terms and Conditions. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">2. Description of Service</h2>
            <p>Thynkk provides market intelligence tools that analyse publicly available Reddit data to surface pain points and trending topics. The Service includes the Pain Point Scanner and Trend Radar features. Outputs are generated using AI and are provided for informational purposes only.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">3. Free and Paid Tiers</h2>
            <p>The free tier grants one (1) lifetime scan with limited results. The Pro tier (${PRO_PRICE_USD}/month) provides {PRO_SCANS_PER_MONTH} scans per calendar month and full report access. Scan counts reset on the first day of each calendar month for paid subscribers. Unused scans do not roll over.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">4. Payment and Billing</h2>
            <p>Pro subscriptions are billed monthly via Stripe. You may cancel at any time. Cancellation takes effect at the end of the current billing period. We do not offer refunds for partial months. If a payment fails, your account will be downgraded to the free tier after a 7-day grace period.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 mt-2 text-[#94A3B8]">
              <li>Use the Service to scrape, reproduce, or redistribute Thynkk output at scale</li>
              <li>Attempt to circumvent scan quotas through IP rotation or other means</li>
              <li>Use outputs to harass, target, or harm individuals identified in Reddit posts</li>
              <li>Reverse-engineer or copy the Service</li>
              <li>Use the Service in any way that violates applicable law</li>
            </ul>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">6. Data and Privacy</h2>
            <p>Thynkk analyses publicly available Reddit content. We do not store personal data about Reddit users beyond what is necessary to provide the Service. For details on how we handle your account data, see our Privacy Policy. We track scan usage by IP address for quota enforcement; this data is stored securely and not shared with third parties.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">7. AI-Generated Content</h2>
            <p>Outputs generated by Thynkk, including theme summaries, opportunity assessments, and trend descriptions, are produced by large language models. They may contain errors, omissions, or inaccuracies. You are responsible for independently verifying any business decisions made using Thynkk output. We make no warranties regarding the accuracy, completeness, or fitness for purpose of AI-generated content.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">8. Intellectual Property</h2>
            <p>The Thynkk platform, branding, and underlying technology are owned by Thynkk. Reddit content analysed by the Service belongs to its respective authors under Reddit&apos;s terms. You retain ownership of any business decisions or products you create using Thynkk output.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Thynkk shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability to you for any claim shall not exceed the amount you paid us in the 30 days preceding the claim.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms at any time. Material changes will be notified via email to registered users. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="font-mono font-bold text-lg text-[#F8FAFC] mb-3">11. Contact</h2>
            <p>For questions about these Terms, email us at <a href="mailto:hello@thynkk.co" className="text-[#6366F1] hover:underline">hello@thynkk.co</a>.</p>
          </section>

        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
